set(CMAKE_CXX_STANDARD 17)

if(BUILD_WITH_ASAN AND BUILD_WITH_TSAN)
    message(FATAL_ERROR "asan and tsan can not be enabled at the same time")
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_compile_options("-Wall")
    add_compile_options("-Wextra")
    add_compile_options("-Wpedantic")
    add_compile_options("-g")
    add_compile_options("-DON_DEBUG")
    if(BUILD_WITH_ASAN)
        message("-- Address sanitizer enabled")
        add_compile_options("-fsanitize=address")
        add_link_options("-fsanitize=address")
    endif()
    if(BUILD_WITH_TSAN)
        message("-- Thread sanitizer enabled")
        add_compile_options("-fsanitize=thread")
        add_link_options("-fsanitize=thread")
    endif()
else()
    add_compile_options("-Wall")
    add_compile_options("-Wextra")
    add_compile_options("-Wpedantic")
endif()